---
# tasks file for site-info
- name: Get IP geolocation data
  community.general.ipinfoio_facts:

- name: "Print System Information"
  debug:
    msg:
      - "System {{ inventory_hostname }}"
      - "    I. Hostname:  {{ inventory_hostname_short }}"
      - "    Hostname:     {{ ansible_hostname }}"
      - "    FQDN:         {{ ansible_fqdn }}"
      - "    IPv4 Addr:    {{ ansible_host }}"
      - "    IPv6 Addr:    {{ ansible_default_ipv6.address | default(none) }}"
      - "    System:       {{ ansible_system }}"
      - "    OS Family:    {{ ansible_os_family }}"
      - "    Distro:       {{ ansible_distribution }}"
      - "    Distro ID:    {{ ansible_lsb.id }}"
      - "    Release       {{ ansible_distribution_release }}"
      - "  Inventory:      {{ inventory_dir }}"
    verbosity: 1

- name: Print Geolocation Information
  debug:
    msg:
      - "City:    {{ city }}"
      - "State:   {{ region }}"
      - "Country: {{ country }}"
      - "Location: {{ loc }}"
    verbosity: 1

- name: "Print Domain Information"
  debug:
    msg:
      - "System {{ inventory_hostname }}"
      - "    Domain:       {{ ansible_domain }}"
      - "    Realm:        {{ ansible_domain|upper }}"
      - "    Workgroup:    {{ ansible_domain.split('.')[0]|upper }}"
      - "    Lets Encrypt: {{ letsencrypt_hosts }}"
    verbosity: 2

- debug:
    msg:
      - "System {{ inventory_hostname }}"
      - "    OS Family:           {{ ansible_os_family.split(' ')[0] | lower }}"
    verbosity: 3

- debug:
    msg:
      - "System {{ inventory_hostname }}"
      - "    OS:           {{ ansible_os | default(none) }}"
      - "    Network OS:   {{ ansible_network_os | default(none) }}"
    verbosity: 2

#    msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
#  when: ansible_default_ipv4.gateway is defined

# Example that prints return information from the previous task

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
    verbosity: 4

# ======================================================================
#
#
#
# ======================================================================
