---
# tasks file for ansible-init
- name: "Localhost: Install ansible.cfg"
  template:
    src: "ansible.cfg.j2"
    dest: ~/.ansible.cfg
    owner: pecan
    group: pecan
    mode: '0644'
  tags:
    - ansible

- name: "Localhost: Install Required Apps"
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  tags:
    - ansible
