---
# tasks file for ansible-init
- name: "Localhost: Install ansible.cfg"
  template:
    src: "{{ role_path }}/templates/ansible.cfg.j2"
    dest: ~/.ansible.cfg
    owner: root
    group: root
    mode: '0644'
  become: yes
  tags:
    - ansible

- name: "Localhost: Install Required Apps"
  package:
    name: "{{ packages }}"
    state: present
  become: yes
  tags:
    - ansible
