---
# # tasks file for password_store
# - name: "Save Domain Users' password to password-store"
#   ansible.builtin.debug:
#     msg: "{{ lookup('community.general.passwordstore', password_store_id + ' create=true length=42 nosymbols=true userpass=' + item.password) }}"
#   vars:
#     password_store_id: "{{ ansible_domain }}/domain_users/{{ item.username }}/password"
#   loop: "{{ domain_users }}"
#   run_once: yes
#   become: no
#   delegate_to: localhost
#   when:
#     - domain_users is defined
#   tags:
#     - never
#     - save-to-password-store

# - name: "Save MySQL Users' password to password-store"
#   ansible.builtin.debug:
#     msg: "{{ lookup('community.general.passwordstore', password_store_id + ' create=true length=42 nosymbols=true userpass=' + item.db_password) }}"
#   vars:
#     password_store_id: "{{ ansible_domain }}/services/mysql/{{ item.db_user }}"
#   loop: "{{ hosts }}"
#   run_once: yes
#   when:
#     - hosts is defined
#   tags:
#     - never
#     - save-to-password-store

- name: "Save Host SSL password to password-store"
  ansible.builtin.debug:
    msg: "{{ lookup('community.general.passwordstore', password_store_id + ' create=true length=42 nosymbols=true') }}"
  vars:
    password_store_id: "{{ ansible_domain }}/hosts/{{ inventory_hostname_short }}/ssl_password"
  tags:
    - never
    - save-to-password-store
