- hosts: all
  ignore_unreachable: yes
  pre_tasks:
    - name: "Create groups based on the Network OS"
      group_by:
        key: "{{ ansible_network_os.split('.')[2] | lower }}"
      when:
        - ansible_network_os is defined

    - name: "Create groups based on the OS Family"
      group_by:
        key: "{{ ansible_os_family | lower }}"
      when:
        - ansible_os_family is defined

    - name: "Create groups based on the System"
      group_by:
        key: "{{ ansible_system | lower }}"
      when:
        - ansible_system is defined

  roles:
    - bloodymage.ansible.info
